# Generated by Django 5.0 on 2024-01-22 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_resena'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='imagen',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
